name = "asd123-website"
main = "src/index.js"
compatibility_date = "2023-12-01"

[assets]
binding = "ASSETS"
directory = "dist"
html_handling = "auto-trailing-slash"

[env.production]
name = "asd123-website"
routes = [{ pattern = "asd123.ai/*", zone_name = "asd123.ai" }]


[env.development]
name = "asd123-website-dev"

[env.production.build]
command = "npm run build"
